import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Save, Eye, Plus, GripVertical, X, FileText, Download } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import CKEditorWrapper from '../../components/Editor/CKEditorWrapper';
import TokenInsertButton from '../../components/Editor/TokenInsertButton';
import templateBuilderService from '../../services/templateBuilder.service';

interface TemplateBlock {
  id: string;
  type: string;
  html: string;
  order: number;
  metadata?: any;
}

interface TemplateMetadata {
  template_title: string;
  template_code: string;
  category: string;
  revision: string;
  effective_date?: string;
  next_review_date?: string;
  cc_number?: string;
  department: string;
  confidentiality: string;
  owner_id: number;
}

export default function TemplateBuilder() {
  const navigate = useNavigate();
  const { templateId } = useParams<{ templateId?: string }>();
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [previewHtml, setPreviewHtml] = useState('');

  // Metadata state
  const [metadata, setMetadata] = useState<TemplateMetadata>({
    template_title: '',
    template_code: '',
    category: 'SOP',
    revision: '01',
    effective_date: '',
    next_review_date: '',
    cc_number: '',
    department: '',
    confidentiality: 'Internal',
    owner_id: user?.id || 0,
  });

  // Blocks state
  const [blocks, setBlocks] = useState<TemplateBlock[]>([]);
  const [editingBlockId, setEditingBlockId] = useState<string | null>(null);
  const [editingBlockContent, setEditingBlockContent] = useState('');
  const editorRefs = useRef<{ [key: string]: any }>({});
  const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>('');
  const [showCodePreview, setShowCodePreview] = useState(false);

  // Token library
  const [tokenLibrary, setTokenLibrary] = useState<any>({});
  const [showTokenPanel, setShowTokenPanel] = useState(false);

  // Load template if editing
  useEffect(() => {
    if (templateId) {
      loadTemplate();
    }
    loadTokenLibrary();
  }, [templateId]);

  const loadTemplate = async () => {
    try {
      setLoading(true);
      const template = await templateBuilderService.getTemplate(parseInt(templateId!));
      if (template.template_data) {
        setMetadata(template.template_data.metadata);
        setBlocks(template.template_data.blocks || []);
      }
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to load template');
    } finally {
      setLoading(false);
    }
  };

  const loadTokenLibrary = async () => {
    try {
      const library = await templateBuilderService.getTokenLibrary();
      setTokenLibrary(library);
    } catch (err) {
      console.error('Error loading token library:', err);
    }
  };

  const handleMetadataChange = (field: keyof TemplateMetadata, value: any) => {
    setMetadata(prev => ({ ...prev, [field]: value }));
    
    // Auto-generate code preview when category, department, or revision changes
    if (field === 'category' || field === 'department' || field === 'revision') {
      generateCodePreview();
    }
  };

  const generateCodePreview = () => {
    if (!metadata.category || !metadata.department || !metadata.revision) {
      setAutoGeneratedCode('');
      return;
    }

    // Generate preview code (client-side estimation)
    // Actual code will be generated by backend
    const deptMap: { [key: string]: string } = {
      'Quality Assurance': 'QA',
      'Quality Control': 'QC',
      'Production': 'PROD',
      'Packaging': 'PKG',
      'R&D': 'R&D',
      'Regulatory': 'REG',
      'Manufacturing': 'MFG',
      'Engineering': 'ENG',
      'Safety': 'SAF',
    };
    
    const deptCode = deptMap[metadata.department] || metadata.department.substring(0, 3).toUpperCase();
    const isForm = metadata.category === 'Form';
    
    if (isForm) {
      // Format: SP-DEPT-NUM-F01-##
      setAutoGeneratedCode(`SP-${deptCode}-XXX-F01-${metadata.revision}`);
    } else {
      // Format: SP-DEPT-NUM-##
      setAutoGeneratedCode(`SP-${deptCode}-XXX-${metadata.revision}`);
    }
  };

  useEffect(() => {
    generateCodePreview();
  }, [metadata.category, metadata.department, metadata.revision]);

  const addBlock = (type: string) => {
    let defaultHtml = '';
    
    // Set default HTML for specific block types
    if (type === 'title') {
      // Default title page structure
      defaultHtml = `
        <img src="/zerokost-logo.png" alt="zerokost Healthcare Pvt. Ltd." style="max-width: 200px; max-height: 60px; height: auto; object-fit: contain; margin-bottom: 12pt;" />
        <table border="1" style="border-collapse: collapse; width: 100%; margin-bottom: 12pt;">
          <tbody>
            <tr>
              <td style="text-align: center; padding: 8pt; font-weight: bold; font-size: 14pt;">STANDARD OPERATING PROCEDURE</td>
            </tr>
          </tbody>
        </table>
        <table border="1" style="border-collapse: collapse; width: 100%;">
          <tbody>
            <tr>
              <td style="padding: 8pt; font-weight: bold; width: 40%;">SOP Title</td>
              <td style="padding: 8pt; width: 60%;">{{TEMPLATE_TITLE}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt; font-weight: bold;">Division/Plant</td>
              <td style="padding: 8pt;">Kurkumbh</td>
            </tr>
            <tr>
              <td style="padding: 8pt; font-weight: bold;">SOP Number</td>
              <td style="padding: 8pt;">{{TEMPLATE_CODE}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt; font-weight: bold;">Initiated Department</td>
              <td style="padding: 8pt;">{{DEPARTMENT}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt; font-weight: bold;">Effective Date</td>
              <td style="padding: 8pt;">{{EFFECTIVE_DATE}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt; font-weight: bold;">CC Number</td>
              <td style="padding: 8pt;">{{CC_NUMBER}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt; font-weight: bold;">Revision</td>
              <td style="padding: 8pt;">{{REVISION}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt; font-weight: bold;">Next Review Date</td>
              <td style="padding: 8pt;">{{NEXT_REVIEW_DATE}}</td>
            </tr>
          </tbody>
        </table>
      `;
    } else if (type === 'signatory_table') {
      defaultHtml = `
        <h2>Document Signatory Page</h2>
        <table border="1" style="border-collapse: collapse; width: 100%;">
          <thead>
            <tr>
              <th style="padding: 8pt; font-weight: bold;">Signature Type</th>
              <th style="padding: 8pt; font-weight: bold;">Name</th>
              <th style="padding: 8pt; font-weight: bold;">Designation</th>
              <th style="padding: 8pt; font-weight: bold;">Department</th>
              <th style="padding: 8pt; font-weight: bold;">Date & Time</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style="padding: 8pt;">Prepared By</td>
              <td style="padding: 8pt;">{{SIGNATORY_PREPARED_NAME}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_PREPARED_DESIGNATION}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_PREPARED_DEPARTMENT}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_PREPARED_DATE}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt;">Checked By</td>
              <td style="padding: 8pt;">{{SIGNATORY_CHECKED_NAME}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_CHECKED_DESIGNATION}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_CHECKED_DEPARTMENT}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_CHECKED_DATE}}</td>
            </tr>
            <tr>
              <td style="padding: 8pt;">Approved By</td>
              <td style="padding: 8pt;">{{SIGNATORY_APPROVED_NAME}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_APPROVED_DESIGNATION}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_APPROVED_DEPARTMENT}}</td>
              <td style="padding: 8pt;">{{SIGNATORY_APPROVED_DATE}}</td>
            </tr>
          </tbody>
        </table>
      `;
    } else if (type === 'annexure_table') {
      defaultHtml = `
        <h2>List of Annexures</h2>
        <table border="1" style="border-collapse: collapse; width: 100%;">
          <thead>
            <tr>
              <th style="padding: 8pt; font-weight: bold; width: 30%;">Annexure No.</th>
              <th style="padding: 8pt; font-weight: bold; width: 70%;">Title</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style="padding: 8pt;"></td>
              <td style="padding: 8pt;"></td>
            </tr>
            <tr>
              <td style="padding: 8pt;"></td>
              <td style="padding: 8pt;"></td>
            </tr>
            <tr>
              <td style="padding: 8pt;"></td>
              <td style="padding: 8pt;"></td>
            </tr>
          </tbody>
        </table>
      `;
    }
    
    const newBlock: TemplateBlock = {
      id: `block_${Date.now()}`,
      type,
      html: defaultHtml,
      order: blocks.length,
      metadata: type === 'heading' ? { heading_text: '' } : {},
    };
    setBlocks(prev => [...prev, newBlock]);
    setEditingBlockId(newBlock.id);
    setEditingBlockContent('');
  };

  const removeBlock = (blockId: string) => {
    setBlocks(prev => prev.filter(b => b.id !== blockId).map((b, idx) => ({ ...b, order: idx })));
    if (editingBlockId === blockId) {
      setEditingBlockId(null);
    }
  };

  const updateBlockContent = (blockId: string, html: string) => {
    setBlocks(prev => prev.map(b => 
      b.id === blockId ? { ...b, html } : b
    ));
  };

  const handleEditorReady = (blockId: string) => (editor: any) => {
    editorRefs.current[blockId] = editor;
    
    // Add token insertion button to toolbar
    const toolbar = editor.ui.componentFactory.create('toolbar');
    // This will be handled by a custom plugin
  };

  const insertToken = (blockId: string, token: string) => {
    const editor = editorRefs.current[blockId];
    if (editor) {
      try {
        // Get current editor data
        const currentData = editor.getData();
        
        // Insert token at cursor position (simple approach: append for now)
        // In a production system, you'd track cursor position
        const tokenText = `{{${token}}}`;
        const newData = currentData + tokenText;
        
        // Set new data
        editor.setData(newData);
        
        // Trigger change event
        const block = blocks.find(b => b.id === blockId);
        if (block) {
          updateBlockContent(blockId, newData);
        }
      } catch (err) {
        console.error('Error inserting token:', err);
        // Fallback: just append to HTML
        const block = blocks.find(b => b.id === blockId);
        if (block) {
          updateBlockContent(blockId, block.html + `{{${token}}}`);
        }
      }
    } else {
      // Fallback: append to block HTML
      const block = blocks.find(b => b.id === blockId);
      if (block) {
        updateBlockContent(blockId, block.html + `{{${token}}}`);
      }
    }
  };

  const handleSave = async (draft: boolean = true) => {
    try {
      setSaving(true);
      setError(null);

      const templateData = {
        metadata,
        blocks: blocks.map(b => ({
          id: b.id,
          type: b.type,
          html: b.html,
          order: b.order,
          metadata: b.metadata || {},
        })),
      };

      if (templateId) {
        await templateBuilderService.updateTemplate(parseInt(templateId), {
          template_data: templateData,
        });
      } else {
        await templateBuilderService.createTemplate({
          template_data: templateData,
        });
      }

      // Navigate to template list or show success
      if (!draft) {
        navigate('/templates');
      }
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to save template');
    } finally {
      setSaving(false);
    }
  };

  const handlePreview = async () => {
    try {
      setLoading(true);
      
      // If template exists, use API preview; otherwise generate client-side
      if (templateId) {
        const preview = await templateBuilderService.previewTemplate(
          parseInt(templateId),
          {}
        );
        const html = preview.blocks.map((b: any) => b.html).join('');
        setPreviewHtml(html);
      } else {
        // Client-side preview: replace tokens with metadata values
        const tokenValues: { [key: string]: string } = {
          TEMPLATE_TITLE: metadata.template_title,
          TEMPLATE_CODE: metadata.template_code,
          REVISION: metadata.revision,
          EFFECTIVE_DATE: metadata.effective_date || '',
          NEXT_REVIEW_DATE: metadata.next_review_date || '',
          CC_NUMBER: metadata.cc_number || '',
          DEPARTMENT: metadata.department,
          CONFIDENTIALITY: metadata.confidentiality,
        };
        
        // Replace tokens in blocks and ensure proper HTML structure
        const previewBlocks = blocks.map((block, index) => {
          let html = block.html;
          
          // Wrap title page blocks in a section for special styling
          if (block.type === 'title' && html) {
            html = `<div class="title-page-section">${html}</div>`;
          }
          
          // Ensure table HTML is properly formatted
          if (block.type === 'table' && html && !html.includes('<table')) {
            // If table block has content but no table tag, wrap it
            html = `<table border="1" style="border-collapse: collapse; width: 100%;"><tbody><tr><td>${html}</td></tr></tbody></table>`;
          }
          
          // Replace tokens
          Object.entries(tokenValues).forEach(([token, value]) => {
            html = html.replace(new RegExp(`\\{\\{${token}\\}\\}`, 'g'), value || `{{${token}}}`);
          });
          
          return html;
        });
        
        setPreviewHtml(previewBlocks.join(''));
      }
      
      setShowPreview(true);
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to generate preview');
    } finally {
      setLoading(false);
    }
  };

  if (loading && !templateId) {
    return (
      <div className="text-center py-12">
        <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        <p className="mt-4 text-gray-600">Loading...</p>
      </div>
    );
  }

  return (
    <div className="flex h-screen overflow-hidden">
      {/* Metadata Panel - Left Sidebar */}
      <div className="w-80 bg-white border-r border-gray-200 overflow-y-auto">
        <div className="p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Template Metadata</h2>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Template Title <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={metadata.template_title}
                onChange={(e) => handleMetadataChange('template_title', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Template Code
                <span className="text-gray-500 text-xs ml-2">(Auto-generated if left empty)</span>
              </label>
              <div className="space-y-2">
                <input
                  type="text"
                  value={metadata.template_code}
                  onChange={(e) => handleMetadataChange('template_code', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
                  placeholder={autoGeneratedCode || "Will be auto-generated"}
                />
                {autoGeneratedCode && !metadata.template_code && (
                  <div className="text-xs text-blue-600 bg-blue-50 px-2 py-1 rounded border border-blue-200">
                    <span className="font-medium">Preview:</span> {autoGeneratedCode}
                    <br />
                    <span className="text-gray-600">XXX will be replaced with sequential number</span>
                  </div>
                )}
                {metadata.template_code && (
                  <button
                    type="button"
                    onClick={() => handleMetadataChange('template_code', '')}
                    className="text-xs text-blue-600 hover:text-blue-800"
                  >
                    Clear to use auto-generated
                  </button>
                )}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Category <span className="text-red-500">*</span>
              </label>
              <select
                value={metadata.category}
                onChange={(e) => handleMetadataChange('category', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
              >
                <option value="SOP">SOP</option>
                <option value="STP">STP</option>
                <option value="Form">Form</option>
                <option value="Report">Report</option>
                <option value="Annexure">Annexure</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Revision <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={metadata.revision}
                onChange={(e) => handleMetadataChange('revision', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
                placeholder="01"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Effective Date
              </label>
              <input
                type="date"
                value={metadata.effective_date}
                onChange={(e) => handleMetadataChange('effective_date', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Next Review Date
              </label>
              <input
                type="date"
                value={metadata.next_review_date}
                onChange={(e) => handleMetadataChange('next_review_date', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                CC Number
              </label>
              <input
                type="text"
                value={metadata.cc_number}
                onChange={(e) => handleMetadataChange('cc_number', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Department <span className="text-red-500">*</span>
              </label>
              <select
                value={metadata.department}
                onChange={(e) => handleMetadataChange('department', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
                required
              >
                <option value="">Select department</option>
                <option value="Quality Assurance">Quality Assurance</option>
                <option value="Quality Control">Quality Control</option>
                <option value="Production">Production</option>
                <option value="Packaging">Packaging</option>
                <option value="R&D">R&D</option>
                <option value="Regulatory">Regulatory</option>
                <option value="Manufacturing">Manufacturing</option>
                <option value="Engineering">Engineering</option>
                <option value="Safety">Safety</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Confidentiality
              </label>
              <select
                value={metadata.confidentiality}
                onChange={(e) => handleMetadataChange('confidentiality', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
              >
                <option value="Public">Public</option>
                <option value="Internal">Internal</option>
                <option value="Restricted">Restricted</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Header */}
        <div className="bg-white border-b border-gray-200 px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate('/templates')}
                className="text-gray-500 hover:text-gray-900"
              >
                <ArrowLeft size={20} />
              </button>
              <h1 className="text-xl font-semibold text-gray-900">
                {templateId ? 'Edit Template' : 'Create Template'}
              </h1>
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={() => setShowTokenPanel(!showTokenPanel)}
                className="px-4 py-2 border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Tokens
              </button>
              <button
                onClick={handlePreview}
                className="px-4 py-2 border border-gray-300 rounded-lg text-sm hover:bg-gray-50 flex items-center gap-2"
              >
                <Eye size={16} />
                Preview
              </button>
              <button
                onClick={() => handleSave(true)}
                disabled={saving}
                className="btn btn-primary flex items-center gap-2"
              >
                <Save size={16} />
                {saving ? 'Saving...' : 'Save Draft'}
              </button>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="bg-red-50 border-b border-red-200 px-6 py-3">
            <p className="text-red-700 text-sm">{error}</p>
          </div>
        )}

        {/* Content Builder */}
        <div className="flex-1 overflow-y-auto bg-gray-50 p-6">
          {/* Add Block Button */}
          <div className="mb-4">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-sm font-medium text-gray-700">Add Block:</span>
              <button
                onClick={() => addBlock('title')}
                className="px-3 py-1.5 bg-white border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Title Page
              </button>
              <button
                onClick={() => addBlock('heading')}
                className="px-3 py-1.5 bg-white border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Heading
              </button>
              <button
                onClick={() => addBlock('paragraph')}
                className="px-3 py-1.5 bg-white border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Paragraph
              </button>
              <button
                onClick={() => addBlock('table')}
                className="px-3 py-1.5 bg-white border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Table
              </button>
              <button
                onClick={() => addBlock('signatory_table')}
                className="px-3 py-1.5 bg-white border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Signatory Table
              </button>
              <button
                onClick={() => addBlock('annexure_table')}
                className="px-3 py-1.5 bg-white border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Annexure Table
              </button>
            </div>
          </div>

          {/* Blocks */}
          <div className="space-y-4">
            {blocks.map((block, index) => (
              <div
                key={block.id}
                className="bg-white rounded-lg border border-gray-200 shadow-sm"
              >
                <div className="flex items-center justify-between p-3 border-b border-gray-200 bg-gray-50">
                  <div className="flex items-center gap-2">
                    <GripVertical className="text-gray-400 cursor-move" size={18} />
                    <span className="text-sm font-medium text-gray-700">
                      {block.type.replace('_', ' ').toUpperCase()}
                    </span>
                  </div>
                  <button
                    onClick={() => removeBlock(block.id)}
                    className="text-red-600 hover:text-red-800"
                  >
                    <X size={18} />
                  </button>
                </div>
                <div className="p-4">
                  {block.type === 'heading' && (
                    <div className="mb-3">
                      <input
                        type="text"
                        placeholder="Heading text"
                        value={block.metadata?.heading_text || ''}
                        onChange={(e) => {
                          setBlocks(prev => prev.map(b =>
                            b.id === block.id
                              ? { ...b, metadata: { ...b.metadata, heading_text: e.target.value } }
                              : b
                          ));
                        }}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm font-semibold"
                      />
                    </div>
                  )}
                  {block.type === 'table' && (
                    <div className="mb-2 p-2 bg-blue-50 border border-blue-200 rounded text-xs text-blue-700">
                      💡 <strong>Tip:</strong> Click the <strong>"Insert Table"</strong> button in the toolbar above to add a table. You can then edit cells and add content.
                    </div>
                  )}
                  <div className="mb-2">
                    <TokenInsertButton
                      onTokenSelect={(token) => {
                        setEditingBlockId(block.id);
                        insertToken(block.id, token);
                      }}
                      tokenLibrary={tokenLibrary}
                    />
                  </div>
                  <CKEditorWrapper
                    initialContent={block.html}
                    onChange={(html) => updateBlockContent(block.id, html)}
                    onReady={handleEditorReady(block.id)}
                    placeholder={
                      block.type === 'table' 
                        ? 'Click "Insert Table" in the toolbar to add a table...'
                        : `Enter ${block.type} content... Use tokens like {{TEMPLATE_TITLE}}`
                    }
                    minHeight="200px"
                  />
                </div>
              </div>
            ))}

            {blocks.length === 0 && (
              <div className="text-center py-12 bg-white rounded-lg border border-gray-200">
                <FileText className="mx-auto text-gray-400 mb-4" size={48} />
                <p className="text-gray-600">No blocks yet. Add a block to get started.</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Token Panel - Right Sidebar */}
      {showTokenPanel && (
        <div className="w-80 bg-white border-l border-gray-200 overflow-y-auto">
          <div className="p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Token Library</h2>
            {Object.entries(tokenLibrary).map(([category, tokens]: [string, any]) => (
              <div key={category} className="mb-6">
                <h3 className="text-sm font-semibold text-gray-700 mb-2">{category}</h3>
                <div className="space-y-1">
                  {tokens.map((token: any) => (
                    <button
                      key={token.name}
                      onClick={() => {
                        if (editingBlockId) {
                          insertToken(editingBlockId, token.name);
                        }
                      }}
                      className="w-full text-left px-3 py-2 text-sm bg-gray-50 hover:bg-gray-100 rounded border border-gray-200"
                      title={token.description}
                    >
                      <code className="text-blue-600">{token.example}</code>
                      <p className="text-xs text-gray-500 mt-1">{token.description}</p>
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Preview Modal */}
      {showPreview && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-6">
          <div className="bg-white rounded-lg shadow-xl w-full max-w-4xl max-h-[90vh] flex flex-col">
            <div className="flex items-center justify-between p-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold">Preview</h2>
              <button
                onClick={() => setShowPreview(false)}
                className="text-gray-500 hover:text-gray-900"
              >
                <X size={20} />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-6 bg-gray-100">
              <div className="template-preview-container">
                <div
                  className="template-preview a4-page"
                  dangerouslySetInnerHTML={{ __html: previewHtml }}
                />
              </div>
              <style>{`
                .template-preview-container {
                  display: flex;
                  justify-content: center;
                  padding: 2rem;
                }
                
                .a4-page {
                  width: 210mm;
                  min-height: 297mm;
                  background: white;
                  padding: 20mm 15mm;
                  margin: 0 auto;
                  box-shadow: 0 0 10px rgba(0,0,0,0.1);
                  font-family: 'Times New Roman', serif;
                  font-size: 12pt;
                  line-height: 1.5;
                }
                
                /* Title page specific styling */
                .a4-page .title-page-section {
                  width: 100%;
                  margin-bottom: 20mm;
                }
                
                .a4-page .title-page-section table {
                  width: 100% !important;
                  border-collapse: collapse;
                  margin: 0;
                  border: 1px solid #000;
                }
                
                .a4-page .title-page-section table th,
                .a4-page .title-page-section table td {
                  border: 1px solid #000;
                  padding: 8pt 10pt;
                  text-align: left;
                  font-size: 11pt;
                }
                
                .a4-page .title-page-section table th {
                  background-color: #f0f0f0;
                  font-weight: 600;
                }
                
                /* Regular tables */
                .a4-page table {
                  border-collapse: collapse;
                  width: 100%;
                  margin: 12pt 0;
                  border: 1px solid #000;
                }
                
                .a4-page table th,
                .a4-page table td {
                  border: 1px solid #000;
                  padding: 6pt 8pt;
                  text-align: left;
                  font-size: 11pt;
                }
                
                .a4-page table th {
                  background-color: #f0f0f0;
                  font-weight: 600;
                }
                
                .a4-page table tr:nth-child(even) {
                  background-color: #fafafa;
                }
                
                /* Headings */
                .a4-page h1 {
                  font-size: 18pt;
                  font-weight: 700;
                  margin-top: 18pt;
                  margin-bottom: 12pt;
                }
                
                .a4-page h2 {
                  font-size: 16pt;
                  font-weight: 600;
                  margin-top: 16pt;
                  margin-bottom: 10pt;
                }
                
                .a4-page h3 {
                  font-size: 14pt;
                  font-weight: 600;
                  margin-top: 14pt;
                  margin-bottom: 8pt;
                }
                
                .a4-page h4, .a4-page h5, .a4-page h6 {
                  font-size: 12pt;
                  font-weight: 600;
                  margin-top: 12pt;
                  margin-bottom: 6pt;
                }
                
                /* Paragraphs */
                .a4-page p {
                  margin: 6pt 0;
                  text-align: justify;
                }
                
                /* Lists */
                .a4-page ul, .a4-page ol {
                  margin: 6pt 0;
                  padding-left: 20pt;
                }
                
                .a4-page li {
                  margin: 3pt 0;
                }
                
                /* Images */
                .a4-page img {
                  max-width: 100%;
                  height: auto;
                  margin: 12pt 0;
                }
                
                /* Page break */
                .a4-page .page-break {
                  page-break-after: always;
                  break-after: page;
                }
                
                /* Text alignment */
                .a4-page .text-center {
                  text-align: center;
                }
                
                .a4-page .text-right {
                  text-align: right;
                }
              `}</style>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

